from uuid import UUID
from datetime import date as date_type
from fastapi import HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from app.models.activity import Activity
from app.models.assignment import Assignment, AssignmentStatus
from app.schemas.schemas import ActivityCreate, ActivityUpdate
from app.services.recurrence_service import RecurrenceService


async def create_activity(
    user_id: UUID, data: ActivityCreate, db: AsyncSession
) -> Activity:
    """
    Create a new activity.

    If recurrence_type != 'none', the parent activity is saved with only
    metadata (no date) and all instance rows are generated by RecurrenceService.
    Otherwise a single activity is saved using activity_date.
    """
    is_recurring = data.recurrence_type and data.recurrence_type != "none"

    # Resolve the effective date for the parent row
    effective_date: date_type
    if is_recurring:
        if not data.recurrence_start_date:
            raise HTTPException(status_code=422, detail="recurrence_start_date is required for recurring activities")
        if not data.recurrence_end_date:
            raise HTTPException(status_code=422, detail="recurrence_end_date is required for recurring activities")
        effective_date = data.recurrence_start_date
    else:
        if not data.activity_date:
            raise HTTPException(status_code=422, detail="activity_date is required for non-recurring activities")
        effective_date = data.activity_date

    activity = Activity(
        user_id=user_id,
        title=data.title,
        category=data.category,
        activity_date=effective_date,
        start_time=data.start_time,
        end_time=data.end_time,
        location=data.location,
        description=data.description,
        recurrence_type=data.recurrence_type or "none",
        recurrence_start_date=data.recurrence_start_date,
        recurrence_end_date=data.recurrence_end_date,
        custom_interval=data.custom_interval,
        custom_interval_unit=data.custom_interval_unit,
        is_recurring_instance=False,
    )

    # Conflict check (only for non-recurring; skip for recurring parents)
    if not is_recurring:
        try:
            conflict_text = await _check_conflicts(user_id, effective_date, db)
            if conflict_text:
                activity.has_conflict = True
                activity.conflict_detail = conflict_text
        except Exception as e:
            print(f"[conflict_check] Warning: {e}")

    db.add(activity)
    await db.flush()
    await db.refresh(activity)

    if is_recurring:
        await RecurrenceService.create_recurring_instances(activity, db)

    return activity


async def get_activities(user_id: UUID, db: AsyncSession) -> list[Activity]:
    result = await db.execute(
        select(Activity)
        .where(Activity.user_id == user_id)
        .order_by(Activity.activity_date.asc())
    )
    return list(result.scalars().all())


async def delete_activity(
    user_id: UUID,
    activity_id: UUID,
    db: AsyncSession,
    delete_series: bool = False,
) -> None:
    result = await db.execute(
        select(Activity).where(
            and_(Activity.id == activity_id, Activity.user_id == user_id)
        )
    )
    activity = result.scalar_one_or_none()
    if not activity:
        raise HTTPException(status_code=404, detail="Activity not found")

    if delete_series and activity.is_recurring_instance and activity.parent_activity_id:
        # Fetch and delete the parent — cascade will remove all instances
        parent_result = await db.execute(
            select(Activity).where(Activity.id == activity.parent_activity_id)
        )
        parent = parent_result.scalar_one_or_none()
        if parent:
            await db.delete(parent)
        else:
            await db.delete(activity)
    else:
        await db.delete(activity)

    await db.flush()


async def update_activity(
    user_id: UUID,
    activity_id: UUID,
    data: ActivityUpdate,
    db: AsyncSession,
    update_series: bool = False,
) -> Activity:
    result = await db.execute(
        select(Activity).where(
            and_(Activity.id == activity_id, Activity.user_id == user_id)
        )
    )
    activity = result.scalar_one_or_none()
    if not activity:
        raise HTTPException(status_code=404, detail="Activity not found")

    if update_series and activity.is_recurring_instance and activity.parent_activity_id:
        # Update parent and regenerate all instances
        parent_result = await db.execute(
            select(Activity).where(Activity.id == activity.parent_activity_id)
        )
        parent = parent_result.scalar_one_or_none()
        if parent:
            for field, value in data.model_dump(exclude_unset=True).items():
                if value is not None:
                    setattr(parent, field, value)
            await db.flush()
            await RecurrenceService.update_recurring_instances(parent, db)
            await db.refresh(parent)
            return parent

    # Update only this instance
    for field, value in data.model_dump(exclude_unset=True).items():
        if value is not None:
            setattr(activity, field, value)
    await db.flush()
    await db.refresh(activity)
    return activity


async def _check_conflicts(user_id: UUID, activity_date, db: AsyncSession) -> str | None:
    """
    Returns a conflict description string if any assignment deadline
    falls on the same date as the activity.
    """
    result = await db.execute(
        select(Assignment.title).where(
            and_(
                Assignment.user_id == user_id,
                Assignment.deadline == activity_date,
                Assignment.status != AssignmentStatus.completed.value,
            )
        )
    )
    titles = [row[0] for row in result.all()]

    if titles:
        return f"Conflicts with: {', '.join(titles)}"
    return None


async def refresh_all_conflicts(user_id: UUID, db: AsyncSession) -> int:
    """Re-run conflict check on all activities. Returns count updated."""
    result = await db.execute(
        select(Activity).where(Activity.user_id == user_id)
    )
    activities = result.scalars().all()
    updated = 0
    for activity in activities:
        conflict_text = await _check_conflicts(user_id, activity.activity_date, db)
        had_conflict = activity.has_conflict
        activity.has_conflict = bool(conflict_text)
        activity.conflict_detail = conflict_text
        if activity.has_conflict != had_conflict:
            updated += 1
    await db.flush()
    return updated
